# Site settings
title: Alan Moore
subtitle: I design and build user interfaces
email: contact@alanmoore.info
description: > # this means to ignore newlines until "baseurl:"
  In which UI/UX and web-head Alan Moore waxes lyrical about stuff relating to his job.
baseurl: ""
staticurl: /static
imageurl: /images
# url: "http://alanmoore.info" # the base hostname & protocol for your site
twitter_username: alanmooredesign
github_username:  alanmoore
linkedin_username: alanmoore1977
github_username: alanmoore

# Build settings
markdown: kramdown
